### ISSUE TITLE
See more Tweets/Instagrams in the past

### ISSUE THREAD

**Issue by lynnandtonic** [meltmedia/whyaz#13]
We were thinking either:
* lazy loading in more of the timeline as you reach the bottom of the page or
* having a "see more" type button at the bottom that loads more

**Comment by lynnandtonic** [comment]
This can be achieved by upgrading to a paid version of Tagboard. @rbarry Do you want to check in on this?

**Comment by rbarry** [comment]
Have a call with tagboard CEO later this week. I'll see if there's a cost-effective option for increasing our viewable feed.
